
language: node_js
node_js:
  - "12"
sudo: false

branches:
  only:
  - master

script:
  - cp report/report.html report/index.html
  - cp report/report.html report/404.html

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: report
  on:
    branch: master
